# Generated by Django 5.2.11 on 2026-03-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzytkownik',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='rola',
            field=models.CharField(choices=[('student', 'Student'), ('profesor', 'Profesor')], default='student', max_length=10),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='grupa_dziekanska',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='numer_indeksu',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
