# Generated by Django 5.2.11 on 2026-03-02 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_alter_snippet_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Łatwe'), ('medium', 'Średnie'), ('hard', 'Trudne')], default='medium', max_length=10)),
                ('time_limit', models.IntegerField(default=1000, help_text='Limit czasu wykonania w milisekundach')),
                ('memory_limit', models.IntegerField(default=256, help_text='Limit pamięci w megabajtach (MB)')),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
