# Generated by Django 5.2.11 on 2026-03-02 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text="Dane wejściowe (np. '2 2' dla zadania o dodawaniu)")),
                ('expected_output', models.TextField(help_text="Oczekiwany wynik (np. '4')")),
                ('is_sample', models.BooleanField(default=False, help_text='Czy to jest test przykładowy widoczny dla użytkownika?')),
                ('points', models.IntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='snippets.task')),
            ],
        ),
    ]
