# Generated by Django 5.2.11 on 2026-03-02 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_testcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(help_text='Kod źródłowy wysłany przez użytkownika')),
                ('language', models.CharField(default='python', max_length=20)),
                ('markdown_explanation', models.TextField(blank=True, help_text='Opcjonalny opis w Markdownie (HU 1.4)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Oczekujące na sprawdzenie'), ('accepted', 'Zaakceptowane (Zaliczony)'), ('wrong_answer', 'Błędna odpowiedź'), ('time_limit', 'Przekroczono limit czasu'), ('memory_limit', 'Przekroczono limit pamięci'), ('error', 'Błąd wykonania (Kompilacji/Runtime)')], default='pending', max_length=20)),
                ('execution_time', models.IntegerField(blank=True, help_text='Czas wykonania w milisekundach (do statystyk HU 1.12)', null=True)),
                ('memory_used', models.IntegerField(blank=True, help_text='Zużycie pamięci w kilobajtach (do statystyk HU 1.12)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='snippets.task')),
            ],
        ),
    ]
