# Generated by Django 5.2.12 on 2026-04-05 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_codegroup_groupmembership_codegroup_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nazwa konkursu', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('strict_mode', models.BooleanField(default=False, help_text='Włącza restrykcje, np. zakaz kopiowania/opuszczania karty')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contests', to=settings.AUTH_USER_MODEL)),
                ('tasks', models.ManyToManyField(related_name='contests', to='snippets.task')),
            ],
        ),
        migrations.CreateModel(
            name='ContestHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('can_edit_tasks', models.BooleanField(default=False, help_text='Czy może dodawać/usuwać zadania z konkursu?')),
                ('can_kick_groups', models.BooleanField(default=False, help_text='Czy może dyskwalifikować grupy?')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('contest', 'user')},
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='hosts',
            field=models.ManyToManyField(related_name='hosted_contests', through='snippets.ContestHost', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ContestParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Kiedy grupa dołączyła do konkursu?')),
                ('is_disqualified', models.BooleanField(default=False, help_text='Czy grupa została zdyskwalifikowana?')),
                ('total_score', models.IntegerField(default=0, help_text='Suma punktów zdobytych przez grupę')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.contest')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.codegroup')),
            ],
            options={
                'unique_together': {('contest', 'group')},
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='participating_groups',
            field=models.ManyToManyField(related_name='joined_contests', through='snippets.ContestParticipation', to='snippets.codegroup'),
        ),
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Szczegóły błędu w zadaniu')),
                ('is_resolved', models.BooleanField(default=False, help_text='Czy sprawa została rozwiązana?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='snippets.task')),
            ],
        ),
    ]
