# Generated by Django 5.2.12 on 2026-04-06 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_contest_contesthost_contest_hosts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='tasks',
        ),
        migrations.CreateModel(
            name='ContestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Kolejność zadania w konkursie (np. 1, 2, 3...)')),
                ('custom_points', models.IntegerField(default=10, help_text='Liczba punktów za zadanie w TYM konkretnym konkursie')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.contest')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.task')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('contest', 'task')},
            },
        ),
    ]
