# Generated by Django 5.2.12 on 2026-04-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_contesttask_alter_contest_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='tasks',
        ),
    ]
