# Generated by Django 5.2.12 on 2026-04-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_remove_contest_tasks_contesttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='tasks',
            field=models.ManyToManyField(related_name='contests', through='snippets.ContestTask', to='snippets.task'),
        ),
    ]
